#include "HttpParser.h"
#include <QRegularExpression>
namespace airb {
namespace { qsizetype delimiter(const QByteArray& b,qsizetype* len){auto p=b.indexOf("\r\n\r\n");if(p>=0){*len=4;return p;}p=b.indexOf("\n\n");if(p>=0){*len=2;return p;}return -1;} QList<QByteArray> lines(QByteArray h){h.replace("\r\n","\n");return h.split('\n');} bool parseNumber(const QByteArray& b,qint64* n){bool ok=false;auto v=b.trimmed().toLongLong(&ok);if(ok&&v>=0)*n=v;return ok&&v>=0;} }
HttpParser::HttpParser(Mode m,qsizetype h,qsizetype b):mode_(m),maxHeaderBytes_(h),maxBodyBytes_(b){}
void HttpParser::reset(){buffer_.clear();remaining_.clear();message_=HttpMessage{};}
bool HttpParser::fail(const QString& e){message_.malformed=true;message_.error=e;return false;}
bool HttpParser::feed(const QByteArray& b){if(message_.complete||message_.malformed)return message_.complete;buffer_+=b;return tryParse(false);}
bool HttpParser::finish(){if(message_.complete||message_.malformed)return message_.complete;return tryParse(true);}
bool HttpParser::parse(const QByteArray& b,Mode m,HttpMessage* out,qsizetype mh,qsizetype mb){HttpParser p(m,mh,mb);p.feed(b);if(!p.isComplete()&&!p.hasError())p.finish();if(out)*out=p.message();return p.isComplete()&&!p.hasError();}
bool HttpParser::tryParse(bool final){qsizetype dl=0;const auto hp=delimiter(buffer_,&dl);if(hp<0){if(buffer_.size()>maxHeaderBytes_)return fail("HTTP header exceeds configured limit");if(final&&!buffer_.isEmpty())return fail("Incomplete HTTP header");return false;}if(hp>maxHeaderBytes_)return fail("HTTP header exceeds configured limit");auto ls=lines(buffer_.left(hp));if(ls.isEmpty()||ls.first().trimmed().isEmpty())return fail("Missing HTTP start line");message_.startLine=ls.takeFirst().trimmed();if(mode_==Mode::Request){QRegularExpression re("^[A-Z!#$%&*+.^_|~-]+\\s+\\S+\\s+HTTP/\\d(?:\\.\\d)?$");if(!re.match(QString::fromLatin1(message_.startLine)).hasMatch())return fail("Malformed HTTP request line");}else{QRegularExpression re("^HTTP/\\d(?:\\.\\d)?\\s+\\d{3}(?:\\s+.*)?$");if(!re.match(QString::fromLatin1(message_.startLine)).hasMatch())return fail("Malformed HTTP status line");}
message_.headers.clear();for(const auto& raw:ls){if(raw.isEmpty())continue;auto c=raw.indexOf(':');if(c<=0)return fail("Malformed HTTP header");auto name=raw.left(c).trimmed(),value=raw.mid(c+1).trimmed();if(name.contains(' ')||name.contains('\t'))return fail("Malformed HTTP header name");message_.headers.append({name,value});}
const qsizetype bodyStart=hp+dl;const auto te=headerValue(message_.headers,"transfer-encoding").toLower();const bool chunked=te.contains("chunked");message_.chunked=chunked;if(chunked){QByteArray decoded;qsizetype pos=bodyStart;while(true){qsizetype eol=buffer_.indexOf("\r\n",pos),sep=2;if(eol<0){eol=buffer_.indexOf('\n',pos);sep=1;}if(eol<0){if(final)return fail("Incomplete chunk size");return false;}auto sizeText=buffer_.mid(pos,eol-pos).trimmed();auto semi=sizeText.indexOf(';');if(semi>=0)sizeText=sizeText.left(semi);bool ok=false;qulonglong size=sizeText.toULongLong(&ok,16);if(!ok)return fail("Malformed chunk size");pos=eol+sep;if(size==0){qsizetype end=buffer_.indexOf("\r\n\r\n",pos);qsizetype used=4;if(end<0){if(buffer_.mid(pos,2)=="\r\n"){end=pos;used=2;}else if(buffer_.mid(pos,1)=="\n"){end=pos;used=1;}else{end=buffer_.indexOf("\n\n",pos);used=2;}}if(end<0){if(final)return fail("Incomplete chunk trailer");return false;}message_.body=decoded;message_.complete=true;remaining_=buffer_.mid(end+used);return true;}if(size>qulonglong(maxBodyBytes_)||decoded.size()+qint64(size)>maxBodyBytes_)return fail("HTTP body exceeds configured limit");if(buffer_.size()-pos<qint64(size)+1){if(final)return fail("Incomplete chunk data");return false;}decoded+=buffer_.mid(pos,qsizetype(size));pos+=qsizetype(size);if(buffer_.mid(pos,2)=="\r\n")pos+=2;else if(buffer_.mid(pos,1)=="\n")pos+=1;else return fail("Malformed chunk terminator");}}
qint64 length=-1;const auto cl=headerValue(message_.headers,"content-length");if(!cl.isEmpty()&&!parseNumber(cl,&length))return fail("Invalid Content-Length");if(length>maxBodyBytes_)return fail("HTTP body exceeds configured limit");if(length>=0){if(buffer_.size()-bodyStart<length){if(final)return fail("Incomplete HTTP body");return false;}message_.body=buffer_.mid(bodyStart,qsizetype(length));remaining_=buffer_.mid(bodyStart+qsizetype(length));message_.complete=true;return true;}
if(mode_==Mode::Request){message_.complete=true;remaining_=buffer_.mid(bodyStart);return true;}auto parts=message_.startLine.split(' ');int status=parts.size()>1?parts.at(1).toInt():0;if((status>=100&&status<200)||status==204||status==304){message_.complete=true;remaining_=buffer_.mid(bodyStart);return true;}if(!final){if(buffer_.size()-bodyStart>maxBodyBytes_)return fail("HTTP body exceeds configured limit");return false;}message_.body=buffer_.mid(bodyStart);if(message_.body.size()>maxBodyBytes_)return fail("HTTP body exceeds configured limit");message_.complete=true;return true;}
}
