#include "ExportService.h"
#include <QFile>
#include <QJsonDocument>
#include <QJsonArray>
#include <QTextStream>
namespace airb {namespace{bool write(const QString&p,const QByteArray&b,QString*e){QFile f(p);if(!f.open(QIODevice::WriteOnly)){if(e)*e=f.errorString();return false;}f.write(b);return true;}QString esc(QString s){s.replace('"',"\"\"");return '"'+s+'"';}}
bool ExportService::json(const QString&p,const QList<TestResult>&rs,QString*e){QJsonArray a;for(const auto&r:rs)a.push_back(toJson(r));QJsonObject root{{"application","AI Relay Station Benchmark & Tester"},{"version",APP_VERSION},{"exportedAt",QDateTime::currentDateTimeUtc().toString(Qt::ISODate)},{"results",a}};return write(p,QJsonDocument(root).toJson(QJsonDocument::Indented),e);}
bool ExportService::csv(const QString&p,const QList<TestResult>&rs,QString*e){QString s="Timestamp,Profile,Protocol,Model,Status,TTFT_ms,Generation_ms,Total_ms,Tokens_per_s,Prompt_tokens,Completion_tokens,Total_tokens,Bytes,Output,Error\r\n";for(const auto&r:rs)s+=QStringList{esc(r.timestamp.toString(Qt::ISODate)),esc(r.profileName),esc(protocolName(r.protocol)),esc(r.model),esc(statusName(r.status)),QString::number(r.metrics.ttftMs,'f',2),QString::number(r.metrics.generationMs,'f',2),QString::number(r.metrics.totalLatencyMs,'f',2),QString::number(r.metrics.tokensPerSecond,'f',2),QString::number(r.metrics.usage.promptTokens),QString::number(r.metrics.usage.completionTokens),QString::number(r.metrics.usage.totalTokens),QString::number(r.metrics.responseBytes),esc(r.output),esc(r.error.message)}.join(',')+"\r\n";return write(p,QByteArray("\xEF\xBB\xBF")+s.toUtf8(),e);}
bool ExportService::markdown(const QString&p,const QList<TestResult>&rs,QString*e){QString s="| Time | Profile | Protocol | Model | Status | TTFT ms | Total ms | Tokens/s | Usage P/C/T |\n|---|---|---|---|---:|---:|---:|---:|---|\n";for(const auto&r:rs)s+=QString("| %1 | %2 | %3 | %4 | %5 | %6 | %7 | %8 | %9/%10/%11 |\n").arg(r.timestamp.toString("HH:mm:ss"),r.profileName,protocolName(r.protocol),r.model,statusName(r.status)).arg(r.metrics.ttftMs,0,'f',1).arg(r.metrics.totalLatencyMs,0,'f',1).arg(r.metrics.tokensPerSecond,0,'f',1).arg(r.metrics.usage.promptTokens).arg(r.metrics.usage.completionTokens).arg(r.metrics.usage.totalTokens);return write(p,s.toUtf8(),e);}}
