#include "ModelService.h"
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QRegularExpression>
#include <QNetworkProxy>
#include <functional>

namespace airb {
namespace {
void applyAuth(QNetworkRequest& req,const Profile&p){req.setRawHeader("Accept","application/json");req.setRawHeader("Authorization",("Bearer "+p.apiKey).toUtf8());if(p.protocol==Protocol::Claude){req.setRawHeader("x-api-key",p.apiKey.toUtf8());req.setRawHeader("anthropic-version","2023-06-01");}for(auto it=p.customHeaders.begin();it!=p.customHeaders.end();++it)req.setRawHeader(it.key().toUtf8(),it.value().toVariant().toString().toUtf8());}
qint64 contextObject(const QJsonObject&o){for(const auto&k:QStringList{"context_length","context_window","max_context_length","input_token_limit","max_input_tokens"}){auto n=parseContext(o.value(k));if(n>0)return n;}for(const auto&container:QStringList{"architecture","capabilities","limit","limits"}){auto x=o.value(container).toObject();for(const auto&k:QStringList{"context","context_length","context_window","input","max_input_tokens"}){auto n=parseContext(x.value(k));if(n>0)return n;}}return -1;}
void setProxy(QNetworkAccessManager& m,const Profile&p){if(p.proxy.mode==ProxyMode::None)m.setProxy(QNetworkProxy::NoProxy);else if(p.proxy.mode==ProxyMode::System)m.setProxy(QNetworkProxy::DefaultProxy);else m.setProxy(QNetworkProxy(p.proxy.mode==ProxyMode::Http?QNetworkProxy::HttpProxy:QNetworkProxy::Socks5Proxy,p.proxy.host,p.proxy.port,p.proxy.username,p.proxy.password));}
}
ModelService::ModelService(QObject* parent):QObject(parent){}
void ModelService::fetch(const Profile& p){cancel();profile_=p;setProxy(manager_,p);adapter_=ProtocolAdapter::create(p.protocol);urls_.clear();for(const auto&u:adapter_->modelUrls(p))if(!urls_.contains(u))urls_.push_back(u);index_=0;budget_.restart();detailsFinishing_=false;tryNext();}
void ModelService::cancel(){++generation_;if(reply_)reply_->abort();reply_=nullptr;for(auto*r:detailReplies_)r->abort();detailReplies_.clear();detailQueue_.clear();activeDetails_=0;detailsFinishing_=false;}
void ModelService::tryNext(){
 if(index_>=urls_.size()){emit modelsReady({},"模型接口不可用，仍可手动输入模型");return;}
 const auto u=urls_[index_++];emit status("正在获取 "+u.toString());QNetworkRequest req(u);applyAuth(req,profile_);req.setTransferTimeout(qMin(profile_.timeoutSeconds*1000,12000));auto*r=manager_.get(req);reply_=r;const auto generation=generation_;
 connect(r,&QNetworkReply::finished,this,[this,u,r,generation]{if(generation!=generation_){r->deleteLater();return;}if(reply_==r)reply_=nullptr;const auto body=r->readAll();const int sc=r->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();if(r->error()==QNetworkReply::NoError&&sc<400){QString e;auto models=adapter_->parseModels(body,&e);if(!models.isEmpty()){r->deleteLater();startDetailLookup(models,u,QString("已从 %2 获取 %1 个模型").arg(models.size()).arg(u.toString()));return;}}r->deleteLater();tryNext();});
}
QList<QUrl> ModelService::detailUrls(const QUrl& modelsUrl,const QString& modelId){QList<QUrl> out;auto add=[&](QString path){QUrl u=modelsUrl;u.setPath(path);u.setQuery(QString());u.setFragment(QString());if(!out.contains(u))out.push_back(u);};QString root=modelsUrl.path();while(root.endsWith('/'))root.chop(1);const QString encoded=QString::fromLatin1(QUrl::toPercentEncoding(modelId));if(root.endsWith("/models"))add(root+"/"+encoded);else add(root+"/models/"+encoded);QString prefix=root;const int pos=prefix.lastIndexOf("/models");if(pos>=0)prefix=prefix.left(pos);while(prefix.endsWith('/'))prefix.chop(1);add(prefix+"/v1/models/"+encoded);add(prefix+"/models/"+encoded);return out;}
void ModelService::startDetailLookup(QList<ModelInfo> models,const QUrl& base,const QString& msg){detailModels_=std::move(models);detailMessage_=msg;detailQueue_.clear();for(int i=0;i<detailModels_.size();++i)if(detailModels_[i].contextLength<0)detailQueue_.enqueue({i,0,detailUrls(base,detailModels_[i].id)});if(detailQueue_.isEmpty()){emit modelsReady(detailModels_,detailMessage_);return;}emit status(QString("正在查询 %1 个模型详情（最多 8 个并发，总预算 12 秒）…").arg(detailQueue_.size()));pumpDetails();}
void ModelService::pumpDetails(){if(detailsFinishing_)return;while(activeDetails_<8&&!detailQueue_.isEmpty()&&budget_.elapsed()<12000){auto task=detailQueue_.dequeue();if(task.urlIndex>=task.urls.size())continue;QNetworkRequest req(task.urls[task.urlIndex]);applyAuth(req,profile_);req.setTransferTimeout(qMax(750,12000-int(budget_.elapsed())));auto*r=manager_.get(req);detailReplies_.insert(r);activeDetails_++;const auto generation=generation_;connect(r,&QNetworkReply::finished,this,[this,r,task,generation]()mutable{detailReplies_.remove(r);if(generation!=generation_){r->deleteLater();return;}activeDetails_--;const int sc=r->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();const auto body=r->readAll();qint64 n=-1;if(r->error()==QNetworkReply::NoError&&sc<400)n=detailContext(body);if(n>0&&task.modelIndex<detailModels_.size()){detailModels_[task.modelIndex].contextLength=n;detailModels_[task.modelIndex].contextSource="API detail";}else if(++task.urlIndex<task.urls.size()&&budget_.elapsed()<12000)detailQueue_.enqueue(task);r->deleteLater();pumpDetails();});}if(activeDetails_==0&&(detailQueue_.isEmpty()||budget_.elapsed()>=12000))finishDetails();}
void ModelService::finishDetails(){if(detailsFinishing_)return;detailsFinishing_=true;if(budget_.elapsed()>=12000)detailQueue_.clear();bool missing=false;for(const auto&m:detailModels_)if(m.contextLength<0){missing=true;break;}if(missing)enrichFromModelsDev(detailModels_,detailMessage_);else{detailsFinishing_=false;emit modelsReady(detailModels_,detailMessage_+" · 已解析全部上下文");}}
qint64 ModelService::detailContext(const QByteArray&body){QJsonParseError e;auto d=QJsonDocument::fromJson(body,&e);if(e.error!=QJsonParseError::NoError||!d.isObject())return -1;auto o=d.object();if(o.value("data").isObject())o=o.value("data").toObject();return contextObject(o);}
void ModelService::enrichFromModelsDev(QList<ModelInfo> models,const QString& msg){emit status("正在从 models.dev 补充剩余上下文窗口…");QNetworkRequest req(QUrl("https://models.dev/api.json"));req.setRawHeader("Accept","application/json");req.setRawHeader("User-Agent","AI-Relay-Bench/1.1");req.setTransferTimeout(qMax(1000,qMin(12000,profile_.timeoutSeconds*1000)));auto*r=manager_.get(req);reply_=r;const auto generation=generation_;connect(r,&QNetworkReply::finished,this,[this,r,generation,models=std::move(models),msg]()mutable{if(generation!=generation_){r->deleteLater();return;}if(reply_==r)reply_=nullptr;const auto b=r->readAll();if(r->error()==QNetworkReply::NoError)mergeCatalog(models,b);int known=0;for(const auto&m:models)known+=m.contextLength>0;r->deleteLater();detailsFinishing_=false;emit modelsReady(models,QString("%1 · 已知上下文 %2/%3").arg(msg).arg(known).arg(models.size()));});}
void ModelService::mergeCatalog(QList<ModelInfo>& models,const QByteArray& bytes){QJsonParseError e;auto doc=QJsonDocument::fromJson(bytes,&e);if(e.error!=QJsonParseError::NoError)return;QHash<QString,qint64> byId;std::function<void(const QJsonValue&,QString)> walk=[&](const QJsonValue&v,QString key){if(v.isObject()){auto o=v.toObject();QString id=o.value("id").toString(key);qint64 ctx=contextObject(o);if(!id.isEmpty()&&ctx>0){byId[id.toLower()]=qMax(byId.value(id.toLower(),-1),ctx);const auto slash=id.section('/',-1);byId[slash.toLower()]=qMax(byId.value(slash.toLower(),-1),ctx);}for(auto it=o.begin();it!=o.end();++it)walk(it.value(),it.key());}else if(v.isArray())for(const auto x:v.toArray())walk(x,key);};walk(doc.isObject()?QJsonValue(doc.object()):QJsonValue(doc.array()),{});for(auto&m:models){if(m.contextLength>0)continue;const QString id=m.id.toLower();qint64 best=byId.value(id,-1);if(best<0)best=byId.value(id.section('/',-1),-1);if(best<0){QString normalized=id;normalized.remove(QRegularExpression("-(latest|preview|\\d{4}[-_]?[01]\\d[-_]?[0-3]\\d)$"));best=byId.value(normalized,-1);}if(best>0){m.contextLength=best;m.contextSource="models.dev";}}}
}
