#include "MainWindow.h"
#include "services/BenchmarkController.h"
#include "services/ModelService.h"
#include "services/ProfileStore.h"
#include "services/ExportService.h"
#include "domain/Statistics.h"
#include "ui/TrendChart.h"
#include "ui/TitleBar.h"
#include "ui/SettingsDialog.h"
#include "ui/ScanDialog.h"
#include "ui/CompareDialog.h"
#include "ui/ThemeManager.h"
#include "i18n/LanguageManager.h"
#include <QtWidgets>
#include <QJsonDocument>
#include <QJsonObject>
#include <QRegularExpression>
#include <algorithm>
#ifdef Q_OS_WIN
#include <windows.h>
#endif

namespace airb {
namespace {
QString displayStatus(TestStatus status) {
 QString source;
 switch (status) {
 case TestStatus::Passed: source=QStringLiteral("通过"); break;
 case TestStatus::Failed: source=QStringLiteral("失败"); break;
 case TestStatus::Timeout: source=QStringLiteral("超时"); break;
 case TestStatus::Cancelled: source=QStringLiteral("已取消"); break;
 case TestStatus::Connecting: source=QStringLiteral("连接中"); break;
 case TestStatus::WaitingFirstToken: source=QStringLiteral("等待首字"); break;
 case TestStatus::Streaming: source=QStringLiteral("流式生成"); break;
 case TestStatus::Queued: source=QStringLiteral("排队中"); break;
 default: source=QStringLiteral("错误"); break;
 }
 return LanguageManager::instance()->trText(source);
}
 QString translateRuntime(const QString& text) {
  auto* l=LanguageManager::instance();
  if (text.startsWith(QStringLiteral("正在获取 "))) return l->trText(QStringLiteral("正在获取 %1")).arg(text.mid(QStringLiteral("正在获取 ").size()));
  if (text.startsWith(QStringLiteral("正在从 models.dev"))) return l->trText(QStringLiteral("正在从 models.dev 补充剩余上下文窗口…"));
  QRegularExpression details(QStringLiteral("^正在查询 (\\d+) 个模型详情（最多 8 个并发，总预算 12 秒）…$"));
  if (auto m=details.match(text); m.hasMatch()) return l->trText(QStringLiteral("正在查询 %1 个模型详情（最多 8 个并发，总预算 12 秒）…")).arg(m.captured(1));
  QRegularExpression fetched(QStringLiteral("^已从 (.+) 获取 (\\d+) 个模型$"));
  if (auto m=fetched.match(text); m.hasMatch()) return l->trText(QStringLiteral("已从 %2 获取 %1 个模型")).arg(m.captured(2),m.captured(1));
  QRegularExpression connecting(QStringLiteral("^连接中 · (.+) · (.+)$"));
  if (auto m=connecting.match(text); m.hasMatch()) return l->trText(QStringLiteral("连接中 · %1 · %2")).arg(m.captured(1),m.captured(2));
  QRegularExpression timeout(QStringLiteral("^请求在 (\\d+) 秒后超时$"));
  if (auto m=timeout.match(text); m.hasMatch()) return l->trText(QStringLiteral("请求在 %1 秒后超时")).arg(m.captured(1));
  return l->trText(text);
 }
}
MainWindow::MainWindow(QWidget*p):QMainWindow(p),controller_(new BenchmarkController(this)),modelService_(new ModelService(this)),store_(new ProfileStore(this)){
 setWindowFlags(Qt::FramelessWindowHint|Qt::WindowSystemMenuHint|Qt::WindowMinMaxButtonsHint);setWindowTitle(QString("AI 中转站测速工具  v%1").arg(APP_VERSION));resize(1520,960);setMinimumSize(1160,760);
 auto*c=new QWidget;c->setObjectName("appRoot");setCentralWidget(c);auto*outer=new QVBoxLayout(c);outer->setContentsMargins(0,0,0,0);outer->setSpacing(0);titleBar_=new TitleBar(this,c);outer->addWidget(titleBar_);auto*body=new QWidget;outer->addWidget(body,1);auto*root=new QVBoxLayout(body);root->setContentsMargins(12,10,12,8);root->setSpacing(10);
 auto*top=new QHBoxLayout;profileBox_=new QComboBox;profileBox_->setMinimumWidth(210);auto*n=new QPushButton("新建");auto*s=new QPushButton("保存");auto*d=new QPushButton("删除");auto*imp=new QPushButton("导入");auto*pexp=new QPushButton("导出");auto*scan=new QPushButton("站点扫描");scan->setObjectName("primaryButton");auto*compare=new QPushButton("横向对比");auto*title=new QLabel("AI 中转站测速");title->setObjectName("contentTitle");title->setStyleSheet("font-size:20px;font-weight:700;");auto*profileLabel=new QLabel("配置");auto*badge=new QLabel("异步 · SSE · HiDPI");badge->setObjectName("featureBadge");top->addWidget(title);top->addSpacing(20);top->addWidget(profileLabel);top->addWidget(profileBox_);top->addWidget(n);top->addWidget(s);top->addWidget(d);top->addWidget(imp);top->addWidget(pexp);top->addWidget(scan);top->addWidget(compare);top->addStretch();top->addWidget(badge);root->addLayout(top);
 auto*split=new QSplitter;split->setChildrenCollapsible(false);root->addWidget(split,1);
 auto*scroll=new QScrollArea;scroll->setWidgetResizable(true);scroll->setMinimumWidth(385);scroll->setMaximumWidth(540);auto*left=new QWidget;left->setObjectName("sidebar");auto*lv=new QVBoxLayout(left);lv->setContentsMargins(10,10,10,10);scroll->setWidget(left);split->addWidget(scroll);
 auto*basic=new QGroupBox("连接与协议");auto*f=new QFormLayout(basic);profileName_=new QLineEdit;protocolBox_=new QComboBox;protocolBox_->addItems({"OpenAI","Claude","Codex"});protocolBox_->setProperty("i18nTranslateItems",true);baseUrl_=new QLineEdit;baseUrl_->setPlaceholderText("https://relay.example.com（可省略 /v1）");baseUrl_->setToolTip("只需填写站点地址；程序会自动探测带 /v1 与不带 /v1 的兼容端点");apiKey_=new QLineEdit;apiKey_->setEchoMode(QLineEdit::Password);showKey_=new QCheckBox("显示");auto*keyRow=new QWidget;auto*kh=new QHBoxLayout(keyRow);kh->setContentsMargins(0,0,0,0);kh->addWidget(apiKey_,1);kh->addWidget(showKey_);modelBox_=new QComboBox;modelBox_->setEditable(true);modelBox_->setInsertPolicy(QComboBox::NoInsert);modelBox_->setPlaceholderText("模型 ID");modelBox_->setToolTip("模型下拉项会显示探测到的上下文窗口；也可自由输入");auto*fetch=new QPushButton("获取模型");auto*mr=new QWidget;auto*mh=new QHBoxLayout(mr);mh->setContentsMargins(0,0,0,0);mh->addWidget(modelBox_,1);mh->addWidget(fetch);timeout_=new QSpinBox;timeout_->setRange(5,60);timeout_->setSuffix(" s");timeout_->setValue(15);context1M_=new QCheckBox("Claude 1M 上下文 Beta 请求头");f->addRow("配置名称",profileName_);f->addRow("协议",protocolBox_);f->addRow("基础 URL",baseUrl_);f->addRow("API 密钥",keyRow);f->addRow("模型",mr);f->addRow("超时",timeout_);f->addRow("Claude Beta",context1M_);lv->addWidget(basic);
 auto*test=new QGroupBox("测试配置");auto*tv=new QVBoxLayout(test);prompt_=new QPlainTextEdit(QString::fromUtf8("请只回复 OK 两个字母，不要输出任何其他内容。"));prompt_->setMaximumHeight(90);regex_=new QLineEdit;regex_->setPlaceholderText("留空 = 精确匹配 OK；填写 = 整串正则");caseSensitive_=new QCheckBox("区分大小写");caseSensitive_->setChecked(true);auto*rr=new QHBoxLayout;rounds_=new QSpinBox;rounds_->setRange(1,100);rounds_->setValue(5);concurrency_=new QSpinBox;concurrency_->setRange(1,8);concurrency_->setValue(3);rr->addWidget(new QLabel("轮数"));rr->addWidget(rounds_);rr->addSpacing(10);rr->addWidget(new QLabel("并发数"));rr->addWidget(concurrency_);tv->addWidget(new QLabel("提示词"));tv->addWidget(prompt_);tv->addWidget(new QLabel("通过匹配"));tv->addWidget(regex_);tv->addWidget(caseSensitive_);tv->addLayout(rr);lv->addWidget(test);
 auto*adv=new QGroupBox("高级请求头（JSON）");auto*av=new QVBoxLayout(adv);headers_=new QPlainTextEdit("{}");headers_->setMaximumHeight(150);headers_->setPlaceholderText("{\n  \"User-Agent\": \"...\"\n}");headerState_=new QLabel("JSON 格式有效");headerState_->setStyleSheet("color:#34d399");auto*presets=new QGridLayout;const QStringList ps={"Codex CLI","Claude Code","Claude 1M","Cherry Studio","ChatBox"};for(int i=0;i<ps.size();++i){auto*b=new QPushButton(ps[i]);presets->addWidget(b,i/3,i%3);connect(b,&QPushButton::clicked,this,[this,x=ps[i]]{applyPreset(x);});}av->addWidget(headers_);av->addWidget(headerState_);av->addLayout(presets);lv->addWidget(adv);
 auto*pg=new QGroupBox("网络代理");auto*pf=new QFormLayout(pg);proxyMode_=new QComboBox;proxyMode_->addItems({"系统代理","直连","HTTP","SOCKS5"});proxyHost_=new QLineEdit;proxyHost_->setPlaceholderText("127.0.0.1");proxyPort_=new QSpinBox;proxyPort_->setRange(0,65535);proxyPort_->setValue(7890);proxyUser_=new QLineEdit;proxyPassword_=new QLineEdit;proxyPassword_->setEchoMode(QLineEdit::Password);pf->addRow("模式",proxyMode_);pf->addRow("主机",proxyHost_);pf->addRow("端口",proxyPort_);pf->addRow("用户名",proxyUser_);pf->addRow("密码",proxyPassword_);lv->addWidget(pg);lv->addStretch();
 auto*right=new QWidget;auto*rv=new QVBoxLayout(right);rv->setContentsMargins(10,0,0,0);split->addWidget(right);split->setStretchFactor(1,1);
 auto*cards=new QHBoxLayout;cards->addWidget(metricCard("状态",&statusValue_));cards->addWidget(metricCard("TTFT",&ttftValue_));cards->addWidget(metricCard("生成耗时",&generationValue_));cards->addWidget(metricCard("速度（Token/s）",&speedValue_));cards->addWidget(metricCard("用量 P / C / T",&usageValue_));rv->addLayout(cards);
 auto*buttons=new QHBoxLayout;singleButton_=new QPushButton("单次测试");singleButton_->setObjectName("primaryButton");batchButton_=new QPushButton("测试全部模型");stabilityButton_=new QPushButton("稳定性 / 抖动");stopButton_=new QPushButton("停止");stopButton_->setObjectName("dangerButton");stopButton_->setEnabled(false);auto*exp=new QPushButton("导出报表");auto*clear=new QPushButton("清空会话");buttons->addWidget(singleButton_);buttons->addWidget(batchButton_);buttons->addWidget(stabilityButton_);buttons->addWidget(stopButton_);buttons->addStretch();buttons->addWidget(exp);buttons->addWidget(clear);rv->addLayout(buttons);progress_=new QProgressBar;progress_->setTextVisible(true);progress_->setRange(0,1);rv->addWidget(progress_);
 auto*tabs=new QTabWidget;auto*live=new QWidget;auto*livev=new QVBoxLayout(live);output_=new QPlainTextEdit;output_->setReadOnly(true);output_->setPlaceholderText("流式输出将在此显示…");livev->addWidget(output_);tabs->addTab(live,"实时输出");auto*history=new QWidget;auto*hv=new QVBoxLayout(history);auto*filterRow=new QHBoxLayout;resultFilter_=new QLineEdit;resultFilter_->setPlaceholderText("筛选模型 / 协议 / 状态 / 错误 …");filterRow->addWidget(new QLabel("筛选"));filterRow->addWidget(resultFilter_);hv->addLayout(filterRow);table_=new QTableWidget;table_->setColumnCount(11);table_->setHorizontalHeaderLabels({"时间","协议","模型","状态","TTFT","生成耗时","总耗时","Token/s","用量 P/C/T","KB","接口"});table_->setSelectionBehavior(QAbstractItemView::SelectRows);table_->setEditTriggers(QAbstractItemView::NoEditTriggers);table_->setAlternatingRowColors(true);table_->horizontalHeader()->setSectionResizeMode(QHeaderView::ResizeToContents);table_->horizontalHeader()->setSectionResizeMode(2,QHeaderView::Stretch);table_->horizontalHeader()->setSectionResizeMode(10,QHeaderView::Stretch);hv->addWidget(table_,1);tabs->addTab(history,"测试结果 / 双击查看原始响应");trend_=new TrendChart;tabs->addTab(trend_,"趋势图");rv->addWidget(tabs,1);summary_=new QLabel("本次会话暂无测试");summary_->setWordWrap(true);summary_->setObjectName("sessionSummary");rv->addWidget(summary_);
 statusBar()->showMessage(LanguageManager::instance()->trText("就绪"));
 connect(profileBox_,qOverload<int>(&QComboBox::currentIndexChanged),this,&MainWindow::loadProfile);connect(n,&QPushButton::clicked,this,&MainWindow::newProfile);connect(s,&QPushButton::clicked,this,&MainWindow::saveProfile);connect(d,&QPushButton::clicked,this,&MainWindow::deleteProfile);connect(imp,&QPushButton::clicked,this,&MainWindow::importProfiles);connect(pexp,&QPushButton::clicked,this,&MainWindow::exportProfiles);connect(scan,&QPushButton::clicked,this,&MainWindow::scanSite);connect(compare,&QPushButton::clicked,this,[this]{CompareDialog dialog(controller_->results(),this);dialog.exec();});connect(fetch,&QPushButton::clicked,this,&MainWindow::fetchModels);connect(showKey_,&QCheckBox::toggled,this,[this](bool x){apiKey_->setEchoMode(x?QLineEdit::Normal:QLineEdit::Password);});connect(headers_,&QPlainTextEdit::textChanged,this,&MainWindow::validateHeaders);connect(singleButton_,&QPushButton::clicked,this,&MainWindow::runSingle);connect(batchButton_,&QPushButton::clicked,this,&MainWindow::runBatch);connect(stabilityButton_,&QPushButton::clicked,this,&MainWindow::runStability);connect(stopButton_,&QPushButton::clicked,controller_,&BenchmarkController::cancelAll);connect(exp,&QPushButton::clicked,this,&MainWindow::exportResults);connect(clear,&QPushButton::clicked,this,[this]{controller_->clear();rowResults_.clear();table_->setRowCount(0);trend_->setResults({});updateSummary();});connect(table_,&QTableWidget::cellDoubleClicked,this,&MainWindow::showRaw);connect(resultFilter_,&QLineEdit::textChanged,this,&MainWindow::filterResults);
 connect(modelService_,&ModelService::modelsReady,this,[this](const QList<ModelInfo>&m,const QString&msg){models_=m;const QString current=modelBox_->currentData().toString().isEmpty()?modelBox_->currentText():modelBox_->currentData().toString();modelBox_->clear();for(const auto&x:m){const int row=modelBox_->count();modelBox_->addItem(QString("%1   ·   %2").arg(x.id,formatContext(x.contextLength)),x.id);modelBox_->setItemData(row,LanguageManager::instance()->trText("上下文：%1，来源：%2").arg(formatContext(x.contextLength),x.contextSource.isEmpty()?LanguageManager::instance()->trText("未知"):x.contextSource),Qt::ToolTipRole);}modelBox_->setCurrentText(current.isEmpty()&&!m.isEmpty()?m.first().id:current);statusBar()->showMessage(translateRuntime(msg),7000);});connect(modelService_,&ModelService::status,this,[this](const QString&s){statusBar()->showMessage(translateRuntime(s));});
 connect(controller_,&BenchmarkController::jobDelta,this,[this](const QString&,const QString&x){output_->moveCursor(QTextCursor::End);output_->insertPlainText(x);});connect(controller_,&BenchmarkController::jobProgress,this,[this](const QString&,const QString&s){statusValue_->setText(translateRuntime(s));});connect(controller_,&BenchmarkController::resultReady,this,&MainWindow::onResult);connect(controller_,&BenchmarkController::batchProgress,this,[this](int d,int t){progress_->setRange(0,qMax(1,t));progress_->setValue(d);});connect(controller_,&BenchmarkController::allFinished,this,[this]{setBusy(false);statusBar()->showMessage(LanguageManager::instance()->trText("全部测试完成"),5000);updateSummary();});connect(controller_,&BenchmarkController::historyWarning,this,[this](const QString&e){statusBar()->showMessage(LanguageManager::instance()->trText("历史记录提示：")+e,7000);});
 connect(titleBar_,&TitleBar::settingsRequested,this,&MainWindow::showSettings);connect(titleBar_,&TitleBar::themeToggleRequested,this,&MainWindow::toggleTheme);connect(LanguageManager::instance(),&LanguageManager::languageChanged,this,&MainWindow::retranslateUi);connect(ThemeManager::instance(),&ThemeManager::themeChanged,this,[this]{titleBar_->retranslate();trend_->update();});
 profiles_=store_->load();if(profiles_.isEmpty()){Profile p;p.name=LanguageManager::instance()->trText("默认配置");p.baseUrl=QUrl("https://api.openai.com/v1");profiles_.push_back(p);}populateProfiles();loadHistory();validateHeaders();retranslateUi();
}
MainWindow::~MainWindow(){saveProfile();}
QWidget*MainWindow::metricCard(const QString&t,QLabel**out){auto*f=new QFrame;f->setObjectName("sidebar");f->setMinimumWidth(135);auto*v=new QVBoxLayout(f);auto*l=new QLabel(t);l->setObjectName("metricTitle");*out=new QLabel("—");(*out)->setObjectName("metricValue");(*out)->setTextInteractionFlags(Qt::TextSelectableByMouse);v->addWidget(l);v->addWidget(*out);return f;}
void MainWindow::populateProfiles(int select){QSignalBlocker b(profileBox_);profileBox_->clear();for(const auto&p:profiles_)profileBox_->addItem(p.name,p.id);if(!profiles_.isEmpty()){const int idx=select>=0&&select<profiles_.size()?select:0;profileBox_->setCurrentIndex(idx);loadProfile(idx);}}
void MainWindow::loadProfile(int i){if(i<0||i>=profiles_.size())return;const auto&p=profiles_[i];profileName_->setText(p.name);protocolBox_->setCurrentIndex(int(p.protocol));baseUrl_->setText(p.baseUrl.toString());apiKey_->setText(p.apiKey);timeout_->setValue(p.timeoutSeconds);context1M_->setChecked(p.context1M);headers_->setPlainText(QString::fromUtf8(QJsonDocument(p.customHeaders).toJson(QJsonDocument::Indented)));modelBox_->setCurrentText(p.defaultModel);proxyMode_->setCurrentIndex(p.proxy.mode==ProxyMode::System?0:p.proxy.mode==ProxyMode::None?1:p.proxy.mode==ProxyMode::Http?2:3);proxyHost_->setText(p.proxy.host);proxyPort_->setValue(p.proxy.port);proxyUser_->setText(p.proxy.username);proxyPassword_->setText(p.proxy.password);}
Profile MainWindow::formProfile()const{Profile p;const int i=profileBox_->currentIndex();if(i>=0&&i<profiles_.size())p.id=profiles_[i].id;p.name=profileName_->text().trimmed().isEmpty()?LanguageManager::instance()->trText("默认配置"):profileName_->text().trimmed();p.baseUrl=QUrl::fromUserInput(baseUrl_->text().trimmed());p.apiKey=apiKey_->text();p.protocol=Protocol(protocolBox_->currentIndex());p.defaultModel=modelBox_->currentData().toString();if(p.defaultModel.isEmpty())p.defaultModel=modelBox_->currentText().section("   ·   ",0,0).trimmed();p.timeoutSeconds=timeout_->value();p.context1M=context1M_->isChecked();p.customHeaders=QJsonDocument::fromJson(headers_->toPlainText().toUtf8()).object();const int pm=proxyMode_->currentIndex();p.proxy.mode=pm==0?ProxyMode::System:pm==1?ProxyMode::None:pm==2?ProxyMode::Http:ProxyMode::Socks5;p.proxy.host=proxyHost_->text().trimmed();p.proxy.port=quint16(proxyPort_->value());p.proxy.username=proxyUser_->text();p.proxy.password=proxyPassword_->text();return p;}
RequestConfig MainWindow::formRequest()const{RequestConfig c;c.model=formProfile().defaultModel;c.prompt=prompt_->toPlainText();c.matchRegex=regex_->text().trimmed();c.caseSensitive=caseSensitive_->isChecked();return c;}
void MainWindow::newProfile(){Profile p;p.name=LanguageManager::instance()->trText("配置 %1").arg(profiles_.size()+1);profiles_.push_back(p);populateProfiles(profiles_.size()-1);}
void MainWindow::deleteProfile(){const int i=profileBox_->currentIndex();if(i<0)return;auto*l=LanguageManager::instance();if(QMessageBox::question(this,l->trText("删除配置"),l->trText("确定要删除当前配置吗？"))==QMessageBox::Yes){profiles_.removeAt(i);if(profiles_.isEmpty()){Profile p;p.name=l->trText("默认配置");profiles_.push_back(p);}store_->save(profiles_);populateProfiles(qMin(i,profiles_.size()-1));}}
void MainWindow::saveProfile(){if(profiles_.isEmpty())return;const int i=qMax(0,profileBox_->currentIndex());if(i>=profiles_.size())return;profiles_[i]=formProfile();store_->save(profiles_);QSignalBlocker b(profileBox_);profileBox_->setItemText(i,profiles_[i].name);statusBar()->showMessage(LanguageManager::instance()->trText("配置已保存"),2500);}
void MainWindow::importProfiles(){auto*l=LanguageManager::instance();const auto filePath=QFileDialog::getOpenFileName(this,l->trText("导入配置"),QString(),l->trText("JSON 配置 (*.json)"));if(filePath.isEmpty())return;QString error;auto imported=ProfileStore::importFile(filePath,&error);if(imported.isEmpty()){QMessageBox::warning(this,l->trText("导入失败"),error);return;}profiles_.append(imported);store_->save(profiles_);populateProfiles(profiles_.size()-imported.size());statusBar()->showMessage(l->trText("已导入 %1 个 API 配置").arg(imported.size()),6000);}
void MainWindow::exportProfiles(){auto*l=LanguageManager::instance();const auto filePath=QFileDialog::getSaveFileName(this,l->trText("导出配置"),"ai-relay-profiles.json",l->trText("JSON 配置 (*.json)"));if(filePath.isEmpty())return;QString error;if(!ProfileStore::exportFile(filePath,profiles_,&error))QMessageBox::critical(this,l->trText("导出失败"),error);else statusBar()->showMessage(l->trText("API 配置已导出"),6000);}
void MainWindow::validateHeaders(){QJsonParseError error;const auto doc=QJsonDocument::fromJson(headers_->toPlainText().toUtf8(),&error);const bool ok=error.error==QJsonParseError::NoError&&doc.isObject();auto*l=LanguageManager::instance();headerState_->setText(ok?l->trText("JSON 格式有效"):l->trText("JSON 格式错误（%1：%2）").arg(error.offset).arg(error.errorString()));headerState_->setStyleSheet(ok?"color:#34d399":"color:#f87171");}
void MainWindow::applyPreset(const QString&name){QJsonParseError e;const auto d=QJsonDocument::fromJson(headers_->toPlainText().toUtf8(),&e);QJsonObject o=d.isObject()?d.object():QJsonObject{};if(name=="Codex CLI"){o["originator"]="codex_exec";o["User-Agent"]="codex_exec/0.147.0 (Windows 10.0.26200; x86_64) unknown (codex_exec; 0.147.0)";o["x-codex-beta-features"]="remote_compaction_v2";o["x-openai-internal-codex-responses-lite"]="true";}else if(name=="Claude Code")o["User-Agent"]="claude-cli/1.0.117 (external, cli)";else if(name=="Claude 1M"){o["anthropic-beta"]="context-1m-2025-08-07";context1M_->setChecked(true);}else if(name=="Cherry Studio")o["User-Agent"]="CherryStudio/1.0";else if(name=="ChatBox")o["User-Agent"]="Chatbox/1.0";headers_->setPlainText(QString::fromUtf8(QJsonDocument(o).toJson(QJsonDocument::Indented)));}
bool MainWindow::validateForm(bool requireModel){auto*l=LanguageManager::instance();QJsonParseError error;const auto doc=QJsonDocument::fromJson(headers_->toPlainText().toUtf8(),&error);if(error.error!=QJsonParseError::NoError||!doc.isObject()){QMessageBox::warning(this,l->trText("请求头无效"),l->trText("高级请求头必须是 JSON 对象"));return false;}const auto profile=formProfile();if(!profile.baseUrl.isValid()||profile.baseUrl.host().isEmpty()||(profile.baseUrl.scheme()!="http"&&profile.baseUrl.scheme()!="https")){QMessageBox::warning(this,l->trText("URL 无效"),l->trText("请输入有效的 HTTP 或 HTTPS 基础 URL"));return false;}if(requireModel&&profile.defaultModel.isEmpty()){QMessageBox::warning(this,l->trText("缺少模型"),l->trText("请输入模型 ID"));return false;}if(prompt_->toPlainText().trimmed().isEmpty()){QMessageBox::warning(this,l->trText("提示词为空"),l->trText("请输入测试提示词"));return false;}if(!regex_->text().isEmpty()){const QRegularExpression re(regex_->text());if(!re.isValid()){QMessageBox::warning(this,l->trText("正则表达式无效"),re.errorString());return false;}}saveProfile();return true;}
void MainWindow::fetchModels(){if(!validateForm(false))return;modelService_->fetch(formProfile());}
void MainWindow::setBusy(bool busy){singleButton_->setEnabled(!busy);batchButton_->setEnabled(!busy);stabilityButton_->setEnabled(!busy);stopButton_->setEnabled(busy);if(busy){output_->clear();statusValue_->setText(LanguageManager::instance()->trText("连接中"));}}
void MainWindow::runSingle(){if(!validateForm())return;setBusy(true);progress_->setRange(0,1);progress_->setValue(0);controller_->runSingle(formProfile(),formRequest());}
void MainWindow::runBatch(){if(!validateForm())return;QStringList ids;for(const auto&m:models_)ids<<m.id;if(ids.isEmpty())ids<<formRequest().model;setBusy(true);progress_->setRange(0,qMax(1,ids.size()));progress_->setValue(0);controller_->runBatch(formProfile(),formRequest(),ids,concurrency_->value(),1);}
void MainWindow::runStability(){if(!validateForm())return;setBusy(true);progress_->setRange(0,rounds_->value());progress_->setValue(0);controller_->runBatch(formProfile(),formRequest(),{formRequest().model},concurrency_->value(),rounds_->value());}
void MainWindow::updateMetricCards(const TestResult&r){auto*l=LanguageManager::instance();statusValue_->setText(r.passed?l->trText("✓ 通过"):r.status==TestStatus::Timeout?l->trText("超时"):l->trText("✕ 失败"));statusValue_->setObjectName(r.passed?"statusPass":"statusFail");statusValue_->style()->unpolish(statusValue_);statusValue_->style()->polish(statusValue_);ttftValue_->setText(r.metrics.ttftMs<0?l->trText("—"):QString::number(r.metrics.ttftMs,'f',1)+" ms");generationValue_->setText(r.metrics.generationMs<0?l->trText("—"):QString::number(r.metrics.generationMs,'f',1)+" ms");speedValue_->setText(r.metrics.tokensPerSecond<0?l->trText("—"):QString::number(r.metrics.tokensPerSecond,'f',1));usageValue_->setText(QString("%1 / %2 / %3%4").arg(r.metrics.usage.promptTokens).arg(r.metrics.usage.completionTokens).arg(r.metrics.usage.totalTokens).arg(r.estimated?" ~":""));}
void MainWindow::onResult(const TestResult&result){updateMetricCards(result);if(!result.error.message.isEmpty())output_->appendPlainText(LanguageManager::instance()->trText("\n[错误] HTTP %1 %2\n%3\n%4").arg(result.error.httpStatus).arg(result.error.reason,result.error.message,result.error.rawSummary.left(1500)));rowResults_.push_back(result);addResultRow(result);updateSummary();}
void MainWindow::addResultRow(const TestResult&r){auto*l=LanguageManager::instance();const int n=table_->rowCount();table_->insertRow(n);const QStringList values={r.timestamp.toString("HH:mm:ss"),protocolName(r.protocol),r.model,r.passed?l->trText("通过"):displayStatus(r.status),r.metrics.ttftMs<0?l->trText("—"):QString::number(r.metrics.ttftMs,'f',1),r.metrics.generationMs<0?l->trText("—"):QString::number(r.metrics.generationMs,'f',1),r.metrics.totalLatencyMs<0?l->trText("—"):QString::number(r.metrics.totalLatencyMs,'f',1),r.metrics.tokensPerSecond<0?l->trText("—"):QString::number(r.metrics.tokensPerSecond,'f',1),QString("%1/%2/%3").arg(r.metrics.usage.promptTokens).arg(r.metrics.usage.completionTokens).arg(r.metrics.usage.totalTokens),QString::number(r.metrics.responseBytes/1024.0,'f',2),r.endpoint};for(int i=0;i<values.size();++i){auto*item=new QTableWidgetItem(values[i]);if(i==3)item->setForeground(r.passed?QColor("#34d399"):QColor("#f87171"));table_->setItem(n,i,item);}table_->scrollToBottom();}
void MainWindow::loadHistory(){const auto rs=controller_->results();for(const auto&r:rs){rowResults_.push_back(r);addResultRow(r);}trend_->setResults(rs);updateSummary();}
void MainWindow::updateSummary(){auto*l=LanguageManager::instance();const auto stats=controller_->stats();if(!stats.total){summary_->setText(l->trText("本次会话暂无测试"));trend_->setResults({});return;}QVector<double>ttft,latency;for(const auto&r:controller_->results()){if(r.metrics.ttftMs>=0)ttft<<r.metrics.ttftMs;if(r.metrics.totalLatencyMs>=0)latency<<r.metrics.totalLatencyMs;}const auto minOf=[](const QVector<double>&v){return v.isEmpty()?-1.0:*std::min_element(v.begin(),v.end());};const auto maxOf=[](const QVector<double>&v){return v.isEmpty()?-1.0:*std::max_element(v.begin(),v.end());};const double jitter=average(ttft)>0?stddev(ttft)/average(ttft)*100:0;const double loss=stats.total?100.0*stats.failed/stats.total:0;summary_->setText(l->trText("测试 %1 · 通过率 %2% · 丢包率 %3% · Token %4\nTTFT（ms） 最小/平均/最大 %5/%6/%7 · P50/P95 %8/%9 · 抖动 %10%\n总耗时（ms） 最小/平均/最大 %11/%12/%13 · P50/P95 %14/%15 · 平均速度 %16 Token/s").arg(stats.total).arg(stats.passRate,0,'f',1).arg(loss,0,'f',1).arg(stats.totalTokens).arg(minOf(ttft),0,'f',1).arg(stats.avgTtft,0,'f',1).arg(maxOf(ttft),0,'f',1).arg(percentile(ttft,.5),0,'f',1).arg(percentile(ttft,.95),0,'f',1).arg(jitter,0,'f',1).arg(minOf(latency),0,'f',1).arg(stats.avgLatency,0,'f',1).arg(maxOf(latency),0,'f',1).arg(percentile(latency,.5),0,'f',1).arg(percentile(latency,.95),0,'f',1).arg(stats.avgSpeed,0,'f',1));trend_->setResults(controller_->results());}
void MainWindow::exportResults(){auto*l=LanguageManager::instance();const auto results=controller_->results();if(results.isEmpty()){QMessageBox::information(this,l->trText("导出报表"),l->trText("当前没有可导出的测试结果"));return;}QString filter=l->trText("JSON (*.json)")+";;"+l->trText("CSV (*.csv)")+";;"+l->trText("Markdown (*.md)");const auto filePath=QFileDialog::getSaveFileName(this,l->trText("导出报表"),"ai-relay-report.json",filter,&filter);if(filePath.isEmpty())return;QString error;const bool ok=filter.startsWith(l->trText("CSV"))?ExportService::csv(filePath,results,&error):filter.startsWith(l->trText("Markdown"))?ExportService::markdown(filePath,results,&error):ExportService::json(filePath,results,&error);if(!ok)QMessageBox::critical(this,l->trText("导出失败"),error);else statusBar()->showMessage(l->trText("已导出 ")+filePath,5000);}
void MainWindow::showRaw(int row,int){if(row<0||row>=rowResults_.size())return;auto*l=LanguageManager::instance();const auto&r=rowResults_[row];auto*dialog=new QDialog(this);dialog->setAttribute(Qt::WA_DeleteOnClose);dialog->resize(1000,700);dialog->setWindowTitle(r.model+" · "+l->trText("原始响应 / SSE"));auto*layout=new QVBoxLayout(dialog);auto*head=new QLabel(QString("%1 · %2 · HTTP %3 %4\n%5").arg(protocolName(r.protocol),r.endpoint).arg(r.error.httpStatus).arg(r.error.reason,r.error.message,r.note));head->setTextInteractionFlags(Qt::TextSelectableByMouse);auto*raw=new QPlainTextEdit(r.rawResponse);raw->setReadOnly(true);raw->setLineWrapMode(QPlainTextEdit::NoWrap);auto*copy=new QPushButton(l->trText("复制"));connect(copy,&QPushButton::clicked,dialog,[raw]{QApplication::clipboard()->setText(raw->toPlainText());});layout->addWidget(head);layout->addWidget(raw,1);layout->addWidget(copy,0,Qt::AlignRight);dialog->show();}
void MainWindow::filterResults(const QString&text){const auto q=text.trimmed();for(int row=0;row<table_->rowCount();++row){bool match=q.isEmpty();if(!match)for(int col=0;col<table_->columnCount();++col)if(table_->item(row,col)&&table_->item(row,col)->text().contains(q,Qt::CaseInsensitive)){match=true;break;}table_->setRowHidden(row,!match);}}
void MainWindow::scanSite(){if(!validateForm(false))return; ScanDialog dialog(formProfile(),modelBox_->currentText(),this); dialog.exec();}
void MainWindow::showSettings(){SettingsDialog dialog(this);dialog.exec();}
void MainWindow::toggleTheme(){auto*t=ThemeManager::instance();t->setMode(t->effectiveTheme()==QStringLiteral("dark")?ThemeMode::Light:ThemeMode::Dark);}
void MainWindow::retranslateUi(){auto*l=LanguageManager::instance();l->retranslate(this);trend_->retranslate();setWindowTitle(l->trText("AI 中转站测速工具")+QStringLiteral("  v")+QStringLiteral(APP_VERSION));titleBar_->retranslate();baseUrl_->setPlaceholderText(l->trText("https://relay.example.com（可省略 /v1）"));baseUrl_->setToolTip(l->trText("只需填写站点地址；程序会自动探测带 /v1 与不带 /v1 的兼容端点"));modelBox_->setPlaceholderText(l->trText("模型 ID"));modelBox_->setToolTip(l->trText("模型下拉项会显示探测到的上下文窗口；也可自由输入"));regex_->setPlaceholderText(l->trText("留空 = 精确匹配 OK；填写 = 整串正则"));output_->setPlaceholderText(l->trText("流式输出将在此显示…"));resultFilter_->setPlaceholderText(l->trText("筛选模型 / 协议 / 状态 / 错误 …"));validateHeaders();const auto results=rowResults_;table_->setRowCount(0);for(const auto&r:results)addResultRow(r);if(!rowResults_.isEmpty())updateMetricCards(rowResults_.constLast());updateSummary();}
bool MainWindow::nativeEvent(const QByteArray& eventType,void* message,qintptr* result){
#ifdef Q_OS_WIN
 Q_UNUSED(eventType);MSG*msg=static_cast<MSG*>(message);if(msg->message==WM_NCHITTEST&&!isMaximized()){const int border=qMax(6,qRound(7*devicePixelRatioF()));RECT wr;GetWindowRect(reinterpret_cast<HWND>(winId()),&wr);const long x=static_cast<short>(LOWORD(msg->lParam)), y=static_cast<short>(HIWORD(msg->lParam));const bool left=x>=wr.left&&x<wr.left+border,right=x<wr.right&&x>=wr.right-border,top=y>=wr.top&&y<wr.top+border,bottom=y<wr.bottom&&y>=wr.bottom-border;if(top&&left)*result=HTTOPLEFT;else if(top&&right)*result=HTTOPRIGHT;else if(bottom&&left)*result=HTBOTTOMLEFT;else if(bottom&&right)*result=HTBOTTOMRIGHT;else if(left)*result=HTLEFT;else if(right)*result=HTRIGHT;else if(top)*result=HTTOP;else if(bottom)*result=HTBOTTOM;else return QMainWindow::nativeEvent(eventType,message,result);return true;}
#else
 Q_UNUSED(eventType);Q_UNUSED(message);Q_UNUSED(result);
#endif
 return QMainWindow::nativeEvent(eventType,message,result);
}
}
